sudo: required
services:
  - docker


before_install:
  - docker build -t temi111/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true temi111/docker-react npm run test

deploy: 
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker" 
  env: "deocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-021130484715"
  bucket_path: "docker"
  on:
    branch: main
access_key_id: $AWS_ACCESS_KEY
secret_access_key: $AWS_SECRET_KEY


##AKIAQJ23ZTPV6LWPIG75


##YiHCDaQqN/AoWNwfGGkKjM0Rrp17n0V5IoqNzzMJ